# Generated by Django 2.2.4 on 2019-08-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=100)),
                ('cate_image', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField()),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_image', models.CharField(max_length=255)),
                ('pro_price', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.SmallIntegerField()),
                ('date_create', models.DateField()),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
