# Generated by Django 2.2.4 on 2019-08-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hien thi'), (0, 'An')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hien thi'), (0, 'An')]),
        ),
    ]
