# Generated by Django 2.2.4 on 2019-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190827_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
