# Generated by Django 2.2.4 on 2019-08-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_cate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bra_id', models.AutoField(primary_key=True, serialize=False)),
                ('bra_name', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(choices=[(1, 'Hien thi'), (0, 'An')])),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pro_year',
            field=models.CharField(default=2018, max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(1, 'Hien thi'), (0, 'An')])),
                ('inventory', models.BooleanField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bra_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Brand'),
            preserve_default=False,
        ),
    ]
