# Generated by Django 2.2.4 on 2019-09-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cate_id',
            new_name='cate',
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hoạt động'), (0, 'Không hoạt động')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hoạt động'), (0, 'Không hoạt động')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hoạt động'), (0, 'Không hoạt động')]),
        ),
    ]
