# Generated by Django 2.2.4 on 2019-08-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190823_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
