# Generated by Django 2.2.4 on 2019-08-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190823_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
